
project_id = "ryuczcsiiyghdnxanofq"
[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
enabled = true

[edge_functions.content-access]
verify_jwt = true

[edge_functions.decrement_balance]
verify_jwt = true

[edge_functions.increment-story-views]
verify_jwt = true

[edge_functions.tron-transaction-verify]
verify_jwt = true

[edge_functions.tron-wallet]
verify_jwt = true

[edge_functions.notify-creator]
verify_jwt = true
