// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwwrlepcivgjokyxgxsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3d3JsZXBjaXZnam9reXhneHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjM2NjUsImV4cCI6MjA2Mjc5OTY2NX0.JtPXJuALt8-h2a99xPXuDB4MdUd5UGxlHfGkyRBi3kM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);