// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryuczcsiiyghdnxanofq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dWN6Y3NpaXlnaGRueGFub2ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDA3MTMsImV4cCI6MjA2MjAxNjcxM30.Cpn4lRh0GZheCACpT6ULlOiQ1h_ZjhggFxyP_Hhuh4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);